[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mewo"
authors = [{name = "duong-dsg", email = "nttduong1@tma.com.vn"}]
dynamic = ["version", "description"]